# Generated by Django 2.1.2 on 2018-12-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='intro',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
